config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'quotations#index'
  resources :quotations, only: [:index, :new, :create, :show, :edit, :destroy]
  resources :items, only: [:new, :create, :destroy]
  resources :clients, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :quotations
  belongs_to :user

  with_options presence: true do
    validates :company
    validates :name
    validates :email
    validates :tel
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :item_quotations
  has_many :item, through: :item_quotations
  #belongs_to :user

  with_options presence: true do
    validates :name
    validates :unit
    validates :unit_price
  end
end

app/models/item_quotation.rb
class ItemQuotation < ApplicationRecord
  belongs_to :item
  belongs_to :quotation
end

app/models/quotation.rb
class Quotation < ApplicationRecord
  has_many :item_quotations
  has_many :quotations, through: :item_quotations
  belongs_to :clients
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items
  has_many :quotations
  has_many :clients
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  def index 
  end

  def new
    @clients = Client.order("created_at DESC")
    @client = Client.new
  end
  
  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to new_client_path
    else
      render :new
    end
  end

  def destroy
    cilient = Client.find(params[:id])
    cilient.destroy
    redirect_to new_client_path
  end

  private

  def client_params
    params.require(:client).permit(:company, :name, :tel, :email).merge(user_id: current_user.id)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index 
  end

  def new
    @items = Item.order("created_at DESC")
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to new_item_path
    else
      render :new
    end
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to new_item_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :standard, :unit, :unit_price, :unit_labor)#.merge(user_id: current_user.id)
  end

end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController

  def index
    @quotations = Quotation.order("created_at DESC")
  end

  def new
    @quotations = Quotation.order("created_at DESC")
    @quotation = Quotation.new
    @items = Item.order("created_at DESC")
    @clients = Client.order("created_at DESC")
  end

  def create
    binding.pry
    @item = Item.find(params[:item_id])
    @quotation = @item.quotation.new(quotation_params)
    if @quotation.save
      redirect_to new_quotation_path
    else
      render :index
    end
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def quotation_params
    params.require(:quotation).permit(:name, :quantity, :standard, :price, :labor).merge(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/views/clients/new.html.erb
<div>
  <%= link_to "ホーム", root_path, class: 'btn'%>
  <%= link_to "見積作成", new_quotation_path, class: 'btn'%>
  <%= link_to "商品登録", new_item_path, class: 'btn'%>
</div>
<div>
  <%= form_with model:@client, method: :post, local: true do |f| %>
    <h1>顧客登録</h1>
    <div><%= f.text_field :company, class:"company-text", id:"item-company", placeholder:"会社名" %></div>
    <div><%= f.text_field :name, class:"name-text", id:"item-name", placeholder:"担当者名" %></div>
    <div><%= f.text_field :tel, class:"tel-text", id:"tel-price", placeholder:"電話番号" %></div>
    <div><%= f.text_field :email, class:"email-text", id:"item-email", placeholder:"メールアドレス" %></div>
    <div><%= f.submit "登録" ,class:"client-btn" %>
  <% end %>
</div>
<div>
  <h1>顧客一覧</h1>
  <% unless @clients.empty? %>
    <% @clients.each do |client|%>
      <div id="client-index", class="client-index">
        <%= client.company %>
        <%= client.name %>
        <%= client.tel %>
        <%= client.email %>
        <%= link_to "編集", "#", method: :get, class: "client-edit-btn" %>
        <%= link_to "削除", client_path(client.id), method: :delete, class:"client-destroy" %>
      </div>
    <% end %>
  <% else %>
    <p> 顧客を登録してください</p>
  <% end %>
</div>

app/views/items/new.html.erb
<div>
  <%= link_to "ホーム", root_path, class: 'btn'%>
  <%= link_to "見積作成", new_quotation_path, class: 'btn'%>
  <%= link_to "顧客登録", new_client_path, class: 'btn'%>
</div>
<div>
  <%= form_with model:@item, method: :post, local: true do |f| %>
    <h1>商品登録</h1>
    <%= f.text_field :name, class:"name-text", id:"item-name", placeholder:"商品名" %>
    <%= f.text_field :standard, class:"standard-text", id:"item-standard", placeholder:"規格" %>
    <%= f.text_field :unit, class:"unit-text", id:"item-unit", placeholder:"単位" %>
    <%= f.text_field :unit_price, class:"unit-price-text", id:"item-unit-price", placeholder:"単価" %>
    <%= f.text_field :unit_labor, class:"unit-labor-text", id:"item-unit-labor", placeholder:"歩掛" %>
    <%= f.submit "登録" ,class:"item-btn" %>
  <% end %>
</div>
<div>
  <h1>商品一覧</h1>
  <% unless @items.empty? %>
    <% @items.each do |item|%>
      <div id="item-index", class="item-index">
        <%= item.name %>
        <%= item.standard %>
        <%= item.unit %>
        <%= item.unit_price %>
        <%= item.unit_labor %>
        <%= link_to "編集", "#", method: :get, class: "quotation-edit-btn" %>
        <%= link_to "削除", item_path(item.id), method: :delete, class:"quotation-destroy" %>
      </div>
    <% end %>
  <% else %>
    <p> 商品を登録してください</p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sekisan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quotations/index.html.erb
<div>
  <% unless user_signed_in? %>
    <%= link_to "ログイン", new_user_session_path, class: 'btn'%>
  <% else %>
    <%= link_to "ログアウト", user_registration_path, method: :delete, class: 'btn'%>
  <% end %>
  <%= link_to "新規登録", new_user_registration_path, class: 'btn'%>
</div>
<div>
  <h1>メニュー</h1>
  <div><%= link_to "見積作成", new_quotation_path, method: :get, class: "quotation-new-btn" %></div>
  <div><%= link_to "顧客登録", new_client_path, method: :get, class: "client-new-btn" %></div>
  <div><%= link_to "商品登録", new_item_path, method: :get, class: "item-new-btn" %></div>
</div>

<div>
  <h1>見積一覧</h1>
  <% unless @quotations.empty? %>
    <% @quotations.each do |quotation|%>
      <div id="quotation-index", class="quotation-index">
        <%= quotation.name %>
        <%= quotation.created_at %>
        <%= link_to "編集", edit_quotation_path, method: :get, class: "quotation-edit-btn" %>
        <%= link_to "削除", quotation_path(quotation.id), method: :delete, class:"quotation-destroy" %>
      </div>
    <% end %>
  <% else %>
    <p> 見積書がありません</p>
  <% end %>
</div>

app/views/quotations/new.html.erb
<div>
  <%= link_to "ホーム", root_path, class: 'btn'%>
  <%= link_to "商品登録", new_item_path, class: 'btn'%>
  <%= link_to "顧客登録", new_client_path, class: 'btn'%>
</div>
<div>
  <h1>物件名登録</h1>
  <%= form_with model:@quotation, method: :post, local: true do |f| %>
    <%= f.text_field :name, class:"name-text", id:"quotation-name", placeholder:"物件名" %>
  <% end %>
  <h1>見積内容</h1>
  <% unless @quotations.empty? %>

  <% else %>
    <p> 商品を選択してください</p>
  <% end %>
    
  <h1>顧客選択</h1>
  <% unless @clients.empty? %>
    <% @clients.each do |client|%>
      <div id="client-index", class="client-index">
        <%= client.company %>
        <%= client.name %>
        <%= client.tel %>
        <%= client.email %>
        <%= link_to "選択", "#", method: :get, class: "client-edit-btn" %>
      </div>
    <% end %>
  <% else %>
    <p> 顧客を登録してください</p>
  <% end %>

  <h1>商品選択</h1>
  <% @items.each do |item|%>
    <div id="quotation-item-index", class="quotation-item-index">
      <%= item.name %>
      <%= item.standard %>
      <%= item.unit %>
      <%= item.unit_price %>
      <%= item.unit_labor %>
      <%= link_to "追加", quotation_path(item.id), method: :post, class: "quotation-add-btn" %>
    </div>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>